[env]
# Use the project name derived from the current directory
PROJECT_NAME = "{{ config_root | basename }}"

# Automatic virtualenv activation
_.python.venv = { path = ".venv", create = true }

[settings]
python.uv_venv_auto = true

[tools]
python = "latest"
ruff = "latest"
uv = "latest"

[tasks.install]
description = "Install dependencies"
alias = "i"
run = "uv sync"
