[env]
# Use the project name derived from the current directory
PROJECT_NAME = "{{ config_root | basename }}"

# Automatic virtualenv activation
_.python.venv = { path = ".venv", create = true }

[settings]
python.uv_venv_auto = true

[tools]
python = "latest"
ruff = "latest"
uv = "latest"

[tasks.install]
description = "Install dependencies"
alias = "i"
run = "uv sync"

[tasks.lint]
description = "Ruff Lint-Check 端ber das gesamte Projekt ausf端hren"
alias = "lc"
run = [
    "uv run ruff check .",
    "uv run ruff format --check .",
]

[tasks.lint-fix]
description = "Ruff Auto-Fix (und Formatierung) 端ber das gesamte Projekt ausf端hren"
alias = "lf"
run = [
    "uv run ruff format .",
    "uv run ruff check --fix ."
]
